name: Elm CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Check that Elm code compiles!
        run: elm make src/Main.elm
